[module "v4l2loopback"]
detect = package:v4l2loopback-kmp-*
module = v4l2loopback
initrd = optional
severity = warning

[module "zfs"]
detect = rootfs:zfs
module = zfs
initrd = required
severity = boot-risk
